### ISSUE TITLE
redstack upgrade python-pip breaks devstack to run again

### ISSUE THREAD

**Issue by cp16net** [hub-cap/reddwarf_lite-integration#51]
Once you run through the redstack process devstack expects python-pip to be in the `/usr/bin/` and when redstack upgrades pip it changes location to the `/usr/local/bin/`.

```
+ sudo PIP_DOWNLOAD_CACHE=/var/cache/pip HTTP_PROXY= HTTPS_PROXY= /usr/bin/pip install --use-mirrors django-nose-selenium PassLib pycrypto==2.3 python-cloudfiles
sudo: /usr/bin/pip: command not found
++ failed
++ local r=1
++ set +o xtrace
```

Current work around for now is `sudo apt-get purge python-pip` and then `sudo apt-get install python-pip` and then run the `redstack install`.

This is the comment in redstack on why we upgrade pip.

```
# The default version of pip Ubuntu installs is old.
```

2 solutions come to mind to fix this so that you can run redstack install multiple times.
1.  fix devstack to use the location of pip where ever it is
2.  link `/usr/local/bin/pip` to `/usr/bin/pip`

**Comment by TimSimpsonR** [comment]
@hub-cap @cp16net Hey guys we need to get serious and fix this issue. Just today I was running redstack and hit this.
